```java
Integer num = Integer.valueOf(100);
Integer num2 = Integer.valueOf(100);
System.out.println(num == num2); // true
// Integer.valueOf 메소드는 값을 가리키는 객체가 없으면 새로 만들고
// 있다면 같은 참조를 가리켜 메모리를 절약한다
```

# Exception (예외)
- 런타임에러가 발생했을 때
```
Exception in thread "main" java.util.InputMismatchException
// 예외가 발생했다. 입력이 맞지 않다.
	at java.base/java.util.Scanner.throwFor(Scanner.java:939)
	at java.base/java.util.Scanner.next(Scanner.java:1594)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2258)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2212)
	at _241122_exception_try_catch.Main.main(Main.java:10)
	// Main.java.:10번째 라인에서 예외가 발생했다
```
```java
import java.util.InputMismatchException;
// 예외도 하나의 클래스이기 때문에 참조해야한다

try {
	System.out.print("1: ");
	int first = scan.nextInt();
	System.out.print("2: ");
	int second = scan.nextInt();
	if (second != 0) {
		int divide = first / second;
		System.out.println("answer: " + divide);
	} else {
		System.out.println("0으로 나눌 수 없다");
	}
	// 에러발생 시점만이 아니라 정상적인 흐름의 코드가 전부 try 내부에 위치해야한다
} catch (InputMismatchException e) {
	System.out.println("정수로 넣어라")
	// 에러로 프로그램이 종료되지 않고 에러임을 알리고 정상흐름으로 돌아감
}
```
```java
// 정상적인 입력이 올때까지 반복하는 코드의 예
while (true) {
	try {
		return SCAN.nextInt();
		// 정상적인 입력을 받으면 리턴한다
	} catch (InputMismatchException e) {
		SCAN.nextLine(); // 입력 버퍼 비우기
		// 정상적인 입력이 들어올 때까지 반복하게 된다
		System.out.println("정수를 넣어라");
		// 사용자에게 문제를 알린다
	}
}
```
- 예외 발생한 라인을 확인하고 제어가능한 상황이라면 코드 수정을 한다
### 예외처리
```java
public int getElement(int[] arr, int index) {
	if (index >= 0 && index < arr.length) {
		return arr[index];
		// 조건부 반환이기 때문에 컴파일에러가 발생한다
	}
	throw new RuntimeException("인덱스 범위 밖.");
	// 임의의 예외상황을 만들어서 쳐내는 키워드 : throw
	// try-catch를 사용해 예외처리를 한다
}
```

